runtime: python37
env: standard
instance_class: F1
entrypoint: gunicorn --bind :$PORT --workers 2 --timeout 600 backend.gunicorn:application

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
